# GoReleaser configuration for YankRun
# See https://goreleaser.com/customization/ for more details

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.FullCommit}}
    binary: yankrun-{{.OS}}-{{.Arch}}
    ignore:
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    name_template: "yankrun-{{.OS}}-{{.Arch}}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
        name_template: "yankrun-{{.OS}}-{{.Arch}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: brasa-ai
    name: yankrun
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"
  footer: |
    ## Installation

    ### Linux/macOS (AMD64)
    ```bash
    curl -L https://github.com/brasa-ai/yankrun/releases/download/{{ .Tag }}/yankrun-linux-amd64.tar.gz -o yankrun-linux-amd64.tar.gz
    tar -xvf yankrun-linux-amd64.tar.gz yankrun-linux-amd64
    chmod +x yankrun-linux-amd64
    sudo mv yankrun-linux-amd64 /usr/local/bin/yankrun
    ```

    ### Linux/macOS (ARM64)
    ```bash
    curl -L https://github.com/brasa-ai/yankrun/releases/download/{{ .Tag }}/yankrun-linux-arm64.tar.gz -o yankrun-linux-arm64.tar.gz
    tar -xvf yankrun-linux-arm64.tar.gz yankrun-linux-arm64
    chmod +x yankrun-linux-arm64
    sudo mv yankrun-linux-arm64 /usr/local/bin/yankrun
    ```

    ### Windows
    ```powershell
    Invoke-WebRequest -Uri https://github.com/brasa-ai/yankrun/releases/download/{{ .Tag }}/yankrun-windows-amd64.zip -OutFile yankrun-windows-amd64.zip
    Expand-Archive -Path yankrun-windows-amd64.zip -DestinationPath .
    Move-Item -Path yankrun-windows-amd64/yankrun-windows-amd64.exe -Destination yankrun.exe
    ```

    ### From Source
    ```bash
    go install github.com/brasa-ai/yankrun@{{ .Tag }}
    ```
